import { PositiveLexiconEntry } from './positiveLexicon';

export const defaultPositiveWords: PositiveLexiconEntry[] = [
    { word: 'syukur', category: 'syukur_kepuasan', sumber: 'Default curated PHA word bank; Linton et al. (2021), JMIR' },
    { word: 'cukup', category: 'syukur_kepuasan', sumber: 'Default curated PHA word bank; Linton et al. (2021), JMIR' },
    { word: 'puas', category: 'syukur_kepuasan', sumber: 'Default curated PHA word bank; Linton et al. (2021), JMIR' },
    { word: 'nikmat', category: 'syukur_kepuasan', sumber: 'Default curated PHA word bank; Linton et al. (2021), JMIR' },
    { word: 'terima', category: 'syukur_kepuasan', sumber: 'Default curated PHA word bank; Linton et al. (2021), JMIR' },
    { word: 'tenang', category: 'ketenangan', sumber: 'Default curated PHA word bank; Vine et al. (2020)' },
    { word: 'damai', category: 'ketenangan', sumber: 'Default curated PHA word bank; Vine et al. (2020)' },
    { word: 'lega', category: 'ketenangan', sumber: 'Default curated PHA word bank; Vine et al. (2020)' },
    { word: 'nyaman', category: 'ketenangan', sumber: 'Default curated PHA word bank; Vine et al. (2020)' },
    { word: 'rileks', category: 'ketenangan', sumber: 'Default curated PHA word bank; Vine et al. (2020)' },
    { word: 'aman', category: 'ketenangan', sumber: 'Default curated PHA word bank; Vine et al. (2020)' },
    { word: 'teduh', category: 'ketenangan', sumber: 'Default curated PHA word bank; Vine et al. (2020)' },
    { word: 'sabar', category: 'ketenangan', sumber: 'Default curated PHA word bank; Vine et al. (2020)' },
    { word: 'fokus', category: 'semangat_capaian', sumber: 'Default curated PHA word bank; Vine et al. (2020)' },
    { word: 'mampu', category: 'semangat_capaian', sumber: 'Default curated PHA word bank; Vine et al. (2020)' },
    { word: 'kuat', category: 'semangat_capaian', sumber: 'Default curated PHA word bank; Vine et al. (2020)' },
    { word: 'usaha', category: 'semangat_capaian', sumber: 'Default curated PHA word bank; Vine et al. (2020)' },
    { word: 'progres', category: 'semangat_capaian', sumber: 'Default curated PHA word bank; Vine et al. (2020)' },
    { word: 'tumbuh', category: 'semangat_capaian', sumber: 'Default curated PHA word bank; Vine et al. (2020)' },
    { word: 'berani', category: 'semangat_capaian', sumber: 'Default curated PHA word bank; Vine et al. (2020)' },
    { word: 'tekun', category: 'semangat_capaian', sumber: 'Default curated PHA word bank; Vine et al. (2020)' },
    { word: 'senang', category: 'kebahagiaan', sumber: 'Default curated PHA word bank; Vine et al. (2020)' },
    { word: 'bahagia', category: 'kebahagiaan', sumber: 'Default curated PHA word bank; Vine et al. (2020)' },
    { word: 'ceria', category: 'kebahagiaan', sumber: 'Default curated PHA word bank; Vine et al. (2020)' },
    { word: 'gembira', category: 'kebahagiaan', sumber: 'Default curated PHA word bank; Vine et al. (2020)' },
    { word: 'bangga', category: 'kebahagiaan', sumber: 'Default curated PHA word bank; Vine et al. (2020)' },
    { word: 'indah', category: 'kebahagiaan', sumber: 'Default curated PHA word bank; Vine et al. (2020)' },
    { word: 'hangat', category: 'kebahagiaan', sumber: 'Default curated PHA word bank; Vine et al. (2020)' },
    { word: 'dukungan', category: 'koneksi_sosial_positif', sumber: 'Default curated PHA word bank; Linton et al. (2021), JMIR' },
    { word: 'bersama', category: 'koneksi_sosial_positif', sumber: 'Default curated PHA word bank; Linton et al. (2021), JMIR' },
    { word: 'sayang', category: 'koneksi_sosial_positif', sumber: 'Default curated PHA word bank; Linton et al. (2021), JMIR' },
    { word: 'peduli', category: 'koneksi_sosial_positif', sumber: 'Default curated PHA word bank; Linton et al. (2021), JMIR' },
    { word: 'teman', category: 'koneksi_sosial_positif', sumber: 'Default curated PHA word bank; Linton et al. (2021), JMIR' },
    { word: 'percaya', category: 'koneksi_sosial_positif', sumber: 'Default curated PHA word bank; Linton et al. (2021), JMIR' },
    { word: 'dibantu', category: 'koneksi_sosial_positif', sumber: 'Default curated PHA word bank; Linton et al. (2021), JMIR' },
    { word: 'diterima', category: 'koneksi_sosial_positif', sumber: 'Default curated PHA word bank; Linton et al. (2021), JMIR' },
];
